services:
  pigeon-web-2025:
    image: pigeonposse/pigeon-web:2025-latest
    ports:
      - "13124:13124" # the web port
    environment:
      GH_TOKEN: ${GH_TOKEN}
      GH_USER: "pigeonposse"
      GH_USER_TYPE: "org" # 'user' or 'org'
      GH_BRANCH: "main"
      DEBUG: false
    restart: always
