version: "3.8"

services:          
  
  pigeonposse-web:

    container_name: ${PIGEONPOSSE_WEB_CONTAINER_NAME:-pigeon-web}
    build: .
    ports:
      - '13128:13124'
      - '1312:1312'
    restart: always


