########################## PIGEONPOSSE DOCKER-COMPOSE #########################
#
# BUILD REPO IN DOCKER WITH DOCKER COMPOSE 
# 
# @description File for build and run project with Docker.
#              you can use npm script 'docker-compose' for run or
#              use cli 'docker-compose up --build -d'
###############################################################################

version: "3.8"


###############################################################################
# SERVICES
###############################################################################

services:          

  #############################################################################
  # RUN DOCKER IMAGE WITH DOCKERFILE
  #############################################################################
  
  pigeon-web:

    container_name: ${PIGEON_WEB_CONTAINER_NAME-pigeon-web}
    build: .
    ports:
      - '${PIGEON_WEB_CONTAINER_PORT-1312}:61312'
    restart: always


########################## PIGEONPOSSE DOCKER-COMPOSE #########################