###############################################################################
# DOCKER COMPOSE BUILD
# 
# @description File for build and run project with Docker.
#              you can use script docker-compose for run
###############################################################################

version: "3.8"


###############################################################################
# SERVICES
###############################################################################

services:          

  #############################################################################
  # Service that return true
  #############################################################################
  pigeon_web:

    container_name: pigeon_web
    build: .
    ports:
      - '1312:3013'
    restart: always


###############################################################################