########################## PIGEONPOSSE DOCKER-COMPOSE #########################
#
# PIGEON WEB IMAGE
# 
# @description Run latest docker image with docker-compose.
#              Easy to use.
# @usage       docker-compose -f docker-compose-dev.yml up --build -d
# @link        https://hub.docker.com/r/pigeonposse/pigeon-web
# @link        https://gethomepage.dev/en/installation/docker/
###############################################################################

version: "3.8"


###############################################################################
# SERVICES
###############################################################################

services:          

  #############################################################################
  # RUN DOCKER IMAGE WITH DOCKERFILE
  #############################################################################
  
  pigeon-web:

    container_name: ${PIGEONPOSSE_WEB_CONTAINER_NAME:-pigeon-web}
    image: pigeonposse/pigeon-web:latest
    restart: always
    ports:
      - '${PIGEONPOSSE_WEB_CONTAINER_PORT:-1312}:61312'
    environment: 
    	PIGEONPOSSE_GH_API_TOKEN:changeToYourGithubApiToken


########################## PIGEONPOSSE DOCKER-COMPOSE #########################