######################### PIGEONPOSSE DOCKER-COMPOSE-DEV ########################
#
# BUILD REPO IN DOCKER WITH DOCKER COMPOSE 
# 
# @description File for build and run project with Docker.
#              you can use npm script 'docker-compose-dev' for run or
#              use cli 'docker-compose -f docker-compose-dev.yml up --build -d'
###############################################################################

version: "3.8"


###############################################################################
# SERVICES
###############################################################################

services:          

  #############################################################################
  # RUN DOCKER IMAGE WITH DOCKERFILE
  #############################################################################
  
  @pigeonposse-web/2023:

    container_name: ${PIGEONPOSSE_WEB_CONTAINER_NAME:-pigeon-web}
    build: .
    ports:
      - '${PIGEONPOSSE_WEB_CONTAINER_PORT:-1312}:61312'
    restart: always


######################### PIGEONPOSSE DOCKER-COMPOSE-DEV ########################