# :schema node_modules/wrangler/config-schema.json
name = "pigeonposse-api"
main = "src/main.ts"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

[triggers]
	crons = [ "*/10 * * * *" ]

[[kv_namespaces]]
	binding = "PIGEONPOSSE_API_KV"
