# ###############################################################################
# # DEPLOY CONTAINER
# ###############################################################################

name: 🐳 Clone and run Docker container

on:
  push:
    branches:
      - main
    tags:
      - '*'


# ###############################################################################
# JOBS
# ###############################################################################

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      SHH_KEY : ${{ secrets.WEB_SERVER_SSH_PRIVATE_KEY }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      WEB_DIR: ${{ secrets.WEB_SERVER_DOCKER_DIR }}
      REPO_URL: https://github.com/${{ github.repository }}
      REPO_NAME: ${{ github.repository | path.basename }}
      ENV_API_TOKEN: "GH_API_TOKEN=${{ secrets.GH_API_TOKEN }}"
      ENV_NAME: "PIGEON_WEB_CONTAINER_NAME=${{ secrets.WEB_DOCKER_NAME }}"
      ENV_PORT: "PIGEON_WEB_CONTAINER_PORT=${{ secrets.WEB_DOCKER_PORT }}"
    

    ###########################################################################
    # STEPS
    ###########################################################################
    
    steps:
    
      - name: 💻 Checkout code
        uses: actions/checkout@v2

      - name: 🔑 Setup SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: $SHH_KEY

      - name: 📋 Clone repository and run Docker container
        run: |
          ssh -t $SSH_HOST '[ -d "$WEB_DIR/$REPO_NAME" ] && cd $REPO_NAME && git pull || git clone $REPO_URL $WEB_DIR/$REPO_NAME'
          ssh -t $SSH_HOST 'cd $WEB_DIR/$REPO_NAME && echo "$ENV_API_TOKEN\n$ENV_NAME\n$ENV_PORT" > .env && sudo docker-compose up --build -d'


# ############################################################################### 