#############################################################################
# BUILD, PUSH, AND DEPLOY
#############################################################################

name: 🌐🐦⚡️ Build & Push Docker Image

on:
  pull_request:
    branches:
      - 2023
  workflow_dispatch:

concurrency: ${{ github.workflow }}-refs/heads/2023

env:
  GITHUB_TOKEN: ${{ github.token }}
  NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
  REPO_TEST: ${{ github.repository }}:2023-test
  REPO_LATEST: ${{ github.repository }}:2023-latest
  CONTEXT_DOCKER: packages/web/.

# #############################################################################
# JOBS
# #############################################################################

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    ###########################################################################
    # STEPS
    ###########################################################################

    steps:

      #########################################################################
      # SETUP
      #########################################################################

      - name: ☑️ Checkout code
        uses: actions/checkout@v2

      - name: ☑️ Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: ☑️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: 🏷 Get version from package.json
        id: package_version
        run: |
          TAG_NAME=$(cat packages/web/package.json | jq -r '.version')
          echo "TAG_NAME=2023-$TAG_NAME" >> $GITHUB_ENV

      #########################################################################
      # LOGIN TO DOCKER
      #########################################################################

      - name: 🐳 Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      #########################################################################
      # TEST DOCKER IMAGE
      #########################################################################

      - name: 🐳📝 (TEST) Build and load to test
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.CONTEXT_DOCKER }}
          load: true
          # platforms: linux/amd64,linux/arm64
          tags: ${{ env.REPO_TEST }}

      - name: 🐳📝 (TEST) execute test
        run: |
          docker run --rm ${{ env.REPO_TEST }}

      #########################################################################
      # BUILD & PUSH
      #########################################################################

      - name: 🐳🚀 Build and push image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.CONTEXT_DOCKER }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ github.repository }}:${{ env.TAG_NAME }}
            ${{ env.REPO_LATEST }}

      - name: 📝 Update Docker Hub metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ github.repository }}:${{ env.TAG_NAME }},${{ env.REPO_LATEST }}

        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}

###############################################################################
